### ISSUE TITLE
Fire Striker is recognized as a shovel

### ISSUE THREAD

**Issue by TheMethodicalJosh** [Pixelated-Studios/SurvivalPlus#10]
I'm not sure if this is intended but the fire striker item is recognized as a shovel, which in doing so not only allows you to use it to dig with it, but it also stops the ability to use it to cook food/items on the go when using the mcMMO plugin because the right click readies "a shovel" for it's special ability in mcMMO.

Minecraft 1.18.2 - PurPur Server

**List of plugins in last screenshot:**

![2022-05-29_17 51 40](https://user-images.githubusercontent.com/48694854/170892813-54b2f1dc-b663-4c60-9441-f9d9668da86d.png)
![2022-05-29_17 53 56](https://user-images.githubusercontent.com/48694854/170892817-17759176-55b8-4761-9864-2335c4009ca0.png)
![2022-05-29_18 00 15](https://user-images.githubusercontent.com/48694854/170892909-c66f45f2-3c41-46b1-a1f1-d54d2de3a2e0.png)

**Comment by expxx** [comment]
Purpur server software is not supported. Try using [paper](https://papermc.io)

**Comment by VetheonDevelops** [comment]
Also, you do have to be aware that the FireStriker technically *is* a Shovel. So other plugins (ones not made with Survival Plus in mind) may still recognize it as a shovel. If this does happen, it's not Survival Plus that is the issue. Unless the item just isn't working, in which case, let me know.

But as Experimentali said above, please use [paper](https://papermc.io/) and not Purpur. Purpur is not supported and it will cause bugs.
