### ISSUE TITLE
[Feature Request] Can't disable firestriker and campfire recipes!

### ISSUE THREAD

**Issue by MrRaposinha** [Pixelated-Studios/SurvivalPlus#11]
There's no way to disable these 2 on the config.

**Comment by VetheonDevelops** [comment]
> There's no way to disable these 2 on the config.

As it stands, there is *no* way to disable the individual core parts of the plugin. This means campfires, firestrikers, and hammers.

We do plan to add this feature to the next update that will also come with several bug fixes, Purpur support, full migration to the Paper API, and removal of some old deprecated dependencies.

This might be a few weeks or maybe even months away. In the meantime, you can disable the restricted crafting, the thirst system, and the nutrition system to sort of "emulate" the removal of those items. Though note they will still be craftable and they will still function.

**Comment by NightSling** [comment]
#17
