### ISSUE TITLE
[Feature Request] Temprature into Scoreboard

### ISSUE THREAD

**Issue by ErythroCraft** [Pixelated-Studios/SurvivalPlus#12]
Hello

Can you add an option to see the temprature in sidebar/scoreboard?

**Comment by VetheonDevelops** [comment]
We can look into this but honestly I'm not sure. Survival Plus doesn't "add" a temperature system, Minecraft actually already has one built into itself.

This is what we use to determine the temperature for the plugin. I'm unsure on if there *is* a way to make it display in the scoreboard, but we can certainly investigate to see if we can. I think that'd be a cool little feature!

**Comment by NightSling** [comment]
#16
