### ISSUE TITLE
[Future Request] Remove scorboards line numbers

### ISSUE THREAD

**Issue by ErythroCraft** [Pixelated-Studios/SurvivalPlus#14]
Hello

Can you give an update to remove line numbers.

red lines I mean
![Bild_2022-06-29_233713419](https://user-images.githubusercontent.com/76217862/176549449-5ec2443d-f20e-4505-9cc6-0acf209e04df.png)

**Comment by expxx** [comment]
It is not possible to remove the numbers without a resource pack. There are a few clients that have the feature to remove them.

**Comment by ErythroCraft** [comment]
Have you got an example to set it on my server resource pack?

**Comment by expxx** [comment]
I believe Badlion does it. No idea how, but they might. Else I think you just have to go into the resourcepack and change it up. Again, no idea how.

**Comment by ErythroCraft** [comment]
Have it.
ItemsAdder has got an option to set it false.

**Comment by ErythroCraft** [comment]
Thanks. Please watch out my other issue
