### ISSUE TITLE
thirst and energy appering in chat while using scoreboard

### ISSUE THREAD

**Issue by Gahtee** [Pixelated-Studios/SurvivalPlus#30]
__**Describe the bug**__
I do have desactivated scoreboard in config but i've put the information about thirst and energy in other scoreboard plugin and the chat wont desactive thirst and energy

__**To Reproduce**__
Im using [sternalboard](https://www.spigotmc.org/resources/sternalboard-lightweight-animated-scoreboard.89245/) plugin
StatusScoreboard: false (survivalplus/config.yml)

in the other scoreboard plugin im using:
%survivalplus_player_thirst_bar_1% (dont think thats necessary 2 of thirst bars)
%survivalplus_player_energy_bar%
%survivalplus_player_hunger_bar_2% (for saturation, 'cause hunger is already shown in hotbar)

__**Expected behavior**__
Expected to dont appear in chat

__**Screenshots**__
![2022-11-06_19 19 15](https://user-images.githubusercontent.com/83777687/200198268-6f0b262d-f893-4a79-984e-4d5ae46bf112.png)
(sede is thirst)
(saturação is saturation)
(energia is energy)

__**Running Environment (please complete the following information):**__
 - LocalHost
 - Paper 245 (git b743144)

__**Server Info (please complete the following information):**__
 - 1.19.2
 - Custom Terrain Generator: not apply for the question but using the default one
 - Average TPS: TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0
 - Amount of Plugins being used: 25

__**Additional context**__
Not a context but english is not my mother language so im sorry for several language errors
and the ip is just a illustration

**Comment by VetheonDevelops** [comment]
In config.yml please find the following lines:

```
  # Shows the players different status levels in a scoreboard
  StatusScoreboard: true
  # Interval for alert messages [in seconds] (Currently used to warn players when thirst/nutrients are low)
  AlertInterval: 20
```

Change `StatusScoreboard` to `false` and change `AlertInterval` to `0` (if `0` doesn't work, use `-1`)

Then reboot your server and ensure that you're using the Status Placeholders in your custom scoreboard (Which I can see you already are, so don't worry about that.)

That should fix your problem.

If it doesn't please re-open this issue and change it's label back to "bug" as that's a bug.

**Comment by Gahtee** [comment]
thanks for ansewing and sorry for the late reply

i tested this code and didnt solved my problem, but reading the question again, i left a information behind, the text appears just when i eat something, eat 1 steak, appear one time. 2 steaks, two times.. theres a way to just remove complety from sending chat information about my hunger and thirst?
```
  # Shows the players different status levels in a scoreboard
  StatusScoreboard: false
  # Interval for alert messages [in seconds] (Currently used to warn players when thirst/nutrients are low)
  AlertInterval: 0
```

> change AlertInterval to 0 (if 0 doesn't work, use -1)

i also tested both and didnt solved
