### ISSUE TITLE
[Future] Support for RealisticSeasons

### ISSUE THREAD

**Issue by ErythroCraft** [Pixelated-Studios/SurvivalPlus#5]
Hi.

Thanks for recoding your plugin. I'm glad.

Can you give support for the plugin RealisticSeasons?
Dieses Plugin erstellt Jahreszeiten für meine Welten.

https://github.com/casperge/RealisticSeasons-issues

**Comment by VetheonDevelops** [comment]
We would love to provide support for it, but is there any particular incompatibility with it? In my experience with it, Survival Plus weather effects do indeed apply for Realistic Seasons weather changes.

Or did you have a specific feature in mind regarding Realistic Seasons?

**Comment by ErythroCraft** [comment]
@VetheonGames 
The feature I mean, is the temperature(in seasons by wandering in bioms) and a different settings of eatable items. 
The temprature we can edit by the realistic season plugin, but not the energie and thurst.

**Your plugin could be the connection between the energy values of food and the seasons with temperatures**

- walking, working, eating, swimming, .... in seasons can get to diffents

For example, the player should warm up when eating food. Or drinking water. A cooling of the body temperature during swimming would also be conceivable.

I'm just not sure if you can implement it.
Something would have to be redesigned.

For example:
- a file of editable items (eatable items)
  1. [minecraft:item_name]
  2. [survivalplus:item_name]
  3. [custom:item_name]

- a setting whether the "RealisticSeasons" plugin is installed.
   usingRealisticSeasonTemprature: true/false

Setting for individual items
Items:
  name: "minecraft:potato"
thirst: [energy setting of survival plus required]
hunger: setting
#part of realistic seasons
effectedWeather: true/false
effectedSeason: true/false

**In a far far future, it can using redstone to warm up boddys. maybe**

**Comment by VetheonDevelops** [comment]
Hey, I've already actually roughed in the hook for Realistic Seasons.

However, do keep in mind that the plugin has very minimal documentation on it's API and has no public maven repository for us to build with. So this is gonna take a *long* time to complete.

Basically, my plan is this:

1. Hook with Realistic Seasons and have Survival Plus watch for calendar and season change events
2. Add a new status effect to **Hot Milk**, **Beetroot Soup**, **Mushroom Soup** and **Coffee** that adds cold resistance
3. Add a new status effect to **Cold Milk** and **all levels of water** that gives heat resistance
4. Add in a new item that changes the seasons
5. Add in a new item that changes the weather
6. Add in a feature that adjusts the amplification of the weather/temp effects in S+ to change based on season and weather temp in Realistic Seasons
7. Add in a calendar item that displays the realistic seasons' calendar.

What do you think about this plan?

**Comment by ErythroCraft** [comment]
@VetheonGames

That's perfect. I like this plan.
Have time.

Thanks very much.

a monthly payment will come next month.

**Comment by ErythroCraft** [comment]
Reopen for more.
