### ISSUE TITLE
Campfire eating furnace's fuel

### ISSUE THREAD

**Issue by ghost** [Pixelated-Studios/SurvivalPlus#8]
After placing campfire underneath the furnace, everything that is fuel put into fuel slot is disappearing

**Comment by expxx** [comment]
Server Software? Logs? Server Version?

**Comment by VetheonDevelops** [comment]
> Server Software? Logs? Server Version?

This was also confirmed. He reported both these issues in the Discord server. I had him put them here too so we wouldn't forget. This, however, happens regardless of the server software.

The plugin simply doesn't know what to do with it as Survival Plus allows you to power furnaces with fire/lava underneath. But when it encounters a campfire it doesn't know what to do.

**Comment by VetheonDevelops** [comment]
https://github.com/Pixelated-Studios/SurvivalPlus/commit/6021eb41dad690dd5aeb664ed1f11299c6ae5f41
